### ISSUE TITLE
Buy Vehshop impossible

### ISSUE THREAD

**Issue by cedricalpatch** [FiveM-Scripts/fs_freeroam#11]
Hello FS team...

- The essentialemode is last version I have download today.
- fs_freeroam same I have download today
- Server is news too I have download today
- Machine is Windows server 2012
- couchdb is news last update I have installed today

So I have installed all resource and all work good but whent I want buy one car I cannot and I have this error :

[https://cdn.discordapp.com/attachments/267682015363465216/327576686440742912/buycar1.PNG](url)

Please lets me know if you have any idea about this error...
Other info I have the 412 error when I run my server but Kanerp have say is not importent!?

Thanks
Cédric
RPF Studio

**Comment by uJakelll** [comment]
Hello did you setup your database correctly, Did you put your username and password in the config file?

**Comment by ghermans** [comment]
2 questions before i can investigate this

- Do you get the 412 error only for **essentialmode** or also for **fs_freeroam**?
- Could you provide us a list of the resources that you are loading?

**Comment by cedricalpatch** [comment]
Hello 

Yes all is right for db and I have found problem... Juste I haved setup the fs_freeroam with new table but we need put in essentialmode table!
So now all work good...
For 412 error yes for 2 one but is not problem all work good and Kanerp have say is normaly for now!
