### ISSUE TITLE
/rmcash command

### ISSUE THREAD

**Issue by Guig2z** [FiveM-Scripts/fs_freeroam#17]
[TEST]

commands.lua 

/addcash ID 500 --> ok
/rmcash ID 500 --> it removes all the cash from player.

**Comment by ghermans** [comment]
I don't see the issue here? 

https://fs-freeroam.readme.io/docs/commands

**Comment by Guig2z** [comment]
Send me a private message on discord i'll send you a clip to show you the problem

**Comment by ghermans** [comment]
The command /rmcash is used like this: **/rmcash ID**
The function for this command is to remove all the cash for that player,

**Comment by Guig2z** [comment]
Oh ok i thought there was an amount.
