### ISSUE TITLE
Vehshop buy issue.

### ISSUE THREAD

**Issue by Guig2z** [FiveM-Scripts/fs_freeroam#19]
When i am in vehshop, i have enogh money to buy a car, but i'm not teleported in it.
But actually i have this vehicule in "personal vehicule".

![vehshop](https://user-images.githubusercontent.com/29654498/27498502-98fc37e2-585f-11e7-92eb-f3e0c61a1318.jpg)

**Comment by ghermans** [comment]
We pushed some updates today regarding the vehicle shop.
So i would like to ask if you are sure that you are using the latest version?

**Comment by Guig2z** [comment]
Yup latest version downloaded today at 8pm (France)

**Comment by ghermans** [comment]
Question is this a fresh db or did you upgrade from 0.1.4?
If so try to remove the databases and restart your **cfx-server**.

**Comment by Guig2z** [comment]
updated from 0.1.4

**Comment by Guig2z** [comment]
Ok i've deleted my databases and retry its OK.

Should announce for everyone who has old databases

**Comment by banegaming** [comment]
I'm having the same issue,
I remove old file from couchDB & delete cache, restart server and still not able to spawn the car.
