### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by Xtrem65** [FiveM-Scripts/fs_freeroam#2]
As the personal vehicle is included in the fs_freeroam db, i think it might be useful to also include a personal inventory.

I forked and am working on it. Feel free to take a look.

Do you agree with this ?
If you don't, i'll create a custom mod. (So i don't bother you ^^)

Thanks.

**Comment by ghermans** [comment]
We are already working on a inventory system, this will be included in the next release.
Also i just checked the change you made to your fork and to be honest it just looks like you did some copy/pasting..
So i am going to decline this.

Regarding the custom mod, you are allowed to write your own gamemode but without changing / using the source from fr/es_freeroam.
in other terms: from scratch.

![againregardinfrknipsel](https://cloud.githubusercontent.com/assets/1594411/25879173/684f0b26-3530-11e7-840d-1064546a181d.PNG)

Thanks for the cooperation.

**Comment by Xtrem65** [comment]
Thanks for the quick answer. Good to hear that this is coming.
 Is there somewhere we can see other upcoming feature ? Can you give me an expected release date ?

To be honest it includes some copy/pasting because :
-  i'm discovering couchDB
-  I wanted to make something clean and coherent with the other uses of freeroam db.

As I said it is not finished yet and has to be polished.

Its sad you are not fully working with github, had i see the inventory coming, i could have spent time porting others mods to your upcoming inventory system instead of doing another...

Anyway,keep up the good work.😀
