### ISSUE TITLE
FrFuel doesnt work with fs_freeroam 0.1.5

### ISSUE THREAD

**Issue by Guig2z** [FiveM-Scripts/fs_freeroam#28]
I dont know if i'm the only one but, since i've install freeroam 0.1.5 frfuel doesnt work anymore.

I suggest the problem come with Blips modificaitons??? Maybe?

**Comment by banegaming** [comment]
mine doesn't work either, and did you got the car working @Guig2z ?

**Comment by Guig2z** [comment]
Fuel doesnt work on car too.

**Comment by JakeRyan1** [comment]
FrFuel is not working with the latest update for fiveM please wait till they update it.

**Comment by ghermans** [comment]
i noticed on the forum that there are issues regarding Frfuel and the latest FiveM update.   

You can find more info regarding this at https://forum.fivem.net/t/for-anyone-wanting-to-know-current-bugs/26693

**Comment by FiveM-Sith** [comment]
FRFuel doesn't relate to us. Check the author's repo for updates.

**Comment by banegaming** [comment]
I reset my essentialmode DB on couch and it works again, don't know if that will help some one.
