### ISSUE TITLE
TowTruck issues

### ISSUE THREAD

**Issue by Guig2z** [FiveM-Scripts/fs_freeroam#29]
I've done some situations tests.

I've ask to a friend to launch a tow truck mission.
I've launch the mission too.

Problem:

-  The 2 tow truck are on the same mission (only 1 vehicle) --> the vehicule (not the tow truck) disapear.

We should probably autorize 1 mission max.
Or change locations of vehicule if there is already a mission launched.

-  Second problem, i've tried to hang my friend's tow truck --> it fucks everything !!! i cant hang off the vehicule, and i can drive all around the map with my cable hanged to the other vehicle. 
For my friend, he can drive normally and doesnt see my cable hanged to his vehicle. (his vehicule is frozen  at the point where i hanged him for me )

**Comment by Guig2z** [comment]
[video.zip](https://github.com/FiveM-Scripts/fs_freeroam/files/1100940/video.zip)

**Comment by chrobione** [comment]
Thanks i will look in to it,
