### ISSUE TITLE
i copied dudes post here

### ISSUE THREAD

**Issue by davedumas0** [FiveM-Scripts/fs_freeroam#7]
How can I make it so that a whitedot appears above a player head whenever he is using ingame VoIP?
and the point in head too.
in scoreboard for for voice indicator
but not work

**Comment by Sinestessia** [comment]
What makiru wants is to show a whitedot or icon above the head of a player whenever said player is talking using in-game VoIP. This is to let the surrounding players know who is it that it is talking in a said moment if they cant recognice the voice or w/e.
